development:
  adapter: postgresql
  encoding: unicode
  database: increaseapi_development
  pool: 5
  username: increaseapi
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: increaseapi_test
  pool: 5
  username: increaseapi
  password: password
  host: localhost
